// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMuFx20cX7LPIlZ3MhVk7gzNQfNk5t1Ag',
    appId: '1:963675411809:web:e3881455d5c6445a852120',
    messagingSenderId: '963675411809',
    projectId: 'flutterapplication-f9cfd',
    authDomain: 'flutterapplication-f9cfd.firebaseapp.com',
    storageBucket: 'flutterapplication-f9cfd.appspot.com',
    measurementId: 'G-VZDVQZLQYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGhquwc3H8blDjxENzxKplxbUpYuYsJUM',
    appId: '1:963675411809:android:fac309468da7c1d9852120',
    messagingSenderId: '963675411809',
    projectId: 'flutterapplication-f9cfd',
    storageBucket: 'flutterapplication-f9cfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN6Imay1xTO5pjXzie-uAparnYPq0cSNo',
    appId: '1:963675411809:ios:f4a51447d377ce33852120',
    messagingSenderId: '963675411809',
    projectId: 'flutterapplication-f9cfd',
    storageBucket: 'flutterapplication-f9cfd.appspot.com',
    iosBundleId: 'com.axiy.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN6Imay1xTO5pjXzie-uAparnYPq0cSNo',
    appId: '1:963675411809:ios:f72df37fe121bf77852120',
    messagingSenderId: '963675411809',
    projectId: 'flutterapplication-f9cfd',
    storageBucket: 'flutterapplication-f9cfd.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMuFx20cX7LPIlZ3MhVk7gzNQfNk5t1Ag',
    appId: '1:963675411809:web:893f2067905c108a852120',
    messagingSenderId: '963675411809',
    projectId: 'flutterapplication-f9cfd',
    authDomain: 'flutterapplication-f9cfd.firebaseapp.com',
    storageBucket: 'flutterapplication-f9cfd.appspot.com',
    measurementId: 'G-GR71KDBEPS',
  );
}
